package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import model.DAO;
import java.util.ArrayList;
import view.ModeloTabela;


public class ListaPedido extends javax.swing.JFrame {

    public ResultSet rs;
    
    public ListaPedido() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        btnCadastro = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnDeleto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 48)); // NOI18N
        jLabel1.setText("Pedidos");

        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTabela);

        btnCadastro.setMnemonic('P');
        btnCadastro.setText("+ Novo Pedido");

        btnRegistrar.setMnemonic('V');
        btnRegistrar.setText("Registrar Venda");

        btnDeleto.setMnemonic('E');
        btnDeleto.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(btnDeleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCadastro)
                    .addComponent(btnRegistrar)
                    .addComponent(btnDeleto))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPedido().setVisible(true);
            }
        });
    }
    
    public void preencherTabela() {
        DAO dao = new DAO();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Data da Venda", "Data de Pagamento", "Tipo de Entrega", "Forma de Pagamento", 
            "Quantidade de Produtos", "Valor Total", "Cliente", "Usuário", "CEP", "Logradouro", "Cidade", "Bairro", "Estado", 
            "Número", "Complemento"};
        rs = dao.localizarPedidos();
        try {
            rs.first();
            do {
                dados.add(new Object[]{rs.getString("codVenda"), rs.getString("dataVenda"), rs.getString("dataPagamento"), 
                    rs.getString("tipoEntrega"), rs.getString("formaPagamento"), rs.getString("quantidade"),rs.getString("valorTotal"), 
                    rs.getString("nome_razao"), rs.getString("login"), rs.getString("cep"), rs.getString("logradouro"), rs.getString("cidade"), 
                    rs.getString("bairro"),  rs.getString("uf"), rs.getString("numero"), rs.getString("complemento")});
            } while (rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:\n" + ex.toString());
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jtTabela.setModel(modelo); // recebe o modelo criado
        jtTabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        jtTabela.getColumnModel().getColumn(0).setResizable(false);
        jtTabela.getColumnModel().getColumn(1).setPreferredWidth(150);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(1).setResizable(true);  // nÃ£o permite alterar o tamanho da coluna
        jtTabela.getColumnModel().getColumn(2).setPreferredWidth(150);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(2).setResizable(true);
        jtTabela.getColumnModel().getColumn(3).setPreferredWidth(100);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(3).setResizable(false);
        jtTabela.getColumnModel().getColumn(4).setPreferredWidth(200);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(4).setResizable(true);
        jtTabela.getColumnModel().getColumn(5).setPreferredWidth(60);
        jtTabela.getColumnModel().getColumn(5).setResizable(false);
        jtTabela.getColumnModel().getColumn(6).setPreferredWidth(150);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(6).setResizable(true);  // nÃ£o permite alterar o tamanho da coluna
        jtTabela.getColumnModel().getColumn(7).setPreferredWidth(150);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(7).setResizable(true);
        jtTabela.getColumnModel().getColumn(8).setPreferredWidth(100);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(8).setResizable(false);
        jtTabela.getColumnModel().getColumn(9).setPreferredWidth(200);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(9).setResizable(true);
        jtTabela.getColumnModel().getColumn(10).setPreferredWidth(200);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(10).setResizable(true);
        jtTabela.getColumnModel().getColumn(11).setPreferredWidth(200);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(11).setResizable(true);
        jtTabela.getColumnModel().getColumn(12).setPreferredWidth(200);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(12).setResizable(true);
        jtTabela.getColumnModel().getColumn(13).setPreferredWidth(200);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(13).setResizable(true);
        jtTabela.getColumnModel().getColumn(14).setPreferredWidth(200);  // define o tamanho das colunas e se serÃ¡ redimensionado ou nÃ£o
        jtTabela.getColumnModel().getColumn(14).setResizable(true);
        jtTabela.getTableHeader().setReorderingAllowed(false);  // NÃ£o permite reordenar as colunas
        jtTabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // NÃ£o permite redimensionar a tabela
        jtTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnDeleto;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtTabela;
    // End of variables declaration//GEN-END:variables
}
